import * as React from 'react'
import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'
import {Analytics} from '@vercel/analytics/react'

const SctoGroteskFont = localFont({
  src: [
    {
      path: '../../public/fonts/Scto_Grotesk_A.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Scto_Grotesk_A_Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--scto-grotesk-a',
  display: 'fallback',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="google-site-verification"
          content="piMpZyWPcXzMqrBx9_0BslPAo9D6-eNrJWRmMn45b1M"
        />
        <meta name="author" content="Gonzalo Stoll" />
        <meta
          name="description"
          content="Meet Ana Laudado, a talented Product Designer and illustration artist from Copenhagen. Explore her work and innovative design solutions here."
        />
        <meta
          name="keywords"
          content="Ana Laudado, portfolio, product design, ux design, ui/ux design"
        />

        {/* OG (Open Graph protocol, for social media) Meta tags */}
        <meta property="og:title" content="Ana Laudado ✦ Portfolio" />
        <meta property="og:image" content="/images/AnitaLaudado.jpeg" />
        <meta
          property="og:description"
          content="Ana Laudado is a Product Designer and illustration artist based in Copenhagen."
        />
        <meta property="og:url" content="https://anitalaudado.com" />
        <meta property="og:type" content="website" />
      </head>
      <body
        className={`flex flex-col h-max min-h-full bg-white dark:bg-black transition-colors duration-500 text-base ${SctoGroteskFont.className}`}
      >
        <Analytics />
        {children}
      </body>
    </html>
  )
}
